[versions]
asciidoc-gradle = "3.3.2"
commons-codec = "1.18.0"
commons-compress = "1.26.2"
groovy = "2.5.17"
jackson = "2.19.1"
javaformat = "0.0.47"
jfrog = "4.31.9"
maven = "3.6.3"
nexus-publish = "1.3.0"
nohttp = "0.0.11"
sonarqube = "2.7.1"
spring = "7.0.0-SNAPSHOT"
test-retry = "1.4.0"
versions = "0.50.0"
version-catalog-update = "0.8.1"

[libraries]
asciidoc-gradle-jvm = { module = "org.asciidoctor:asciidoctor-gradle-jvm", version.ref = "asciidoc-gradle" }
commons-codec = { module = "commons-codec:commons-codec", version.ref = "commons-codec" }
commons-compress = { module = "org.apache.commons:commons-compress", version.ref = "commons-compress" }
groovy-all = { module = "org.codehaus.groovy:groovy-all", version.ref = "groovy" }
jackson-bom = { module = "com.fasterxml.jackson:jackson-bom", version.ref = "jackson" }
jackson-databind = { module = "com.fasterxml.jackson.core:jackson-databind", version.ref = "jackson" }
javaformat-checkstyle = { module = "io.spring.javaformat:spring-javaformat-checkstyle", version.ref = "javaformat" }
javaformat-gradle = { module = "io.spring.javaformat:spring-javaformat-gradle-plugin", version.ref = "javaformat" }
jfrog-build-extractor-gradle = { module = "org.jfrog.buildinfo:build-info-extractor-gradle", version.ref = "jfrog" }
maven-embedder = { module = "org.apache.maven:maven-embedder", version.ref = "maven" }
nexus-publish = { module = "io.github.gradle-nexus:publish-plugin", version.ref = "nexus-publish" }
nohttp-gradle = { module = "io.spring.nohttp:nohttp-gradle", version.ref = "nohttp" }
sonarqube-gradle = { module = "org.sonarsource.scanner.gradle:sonarqube-gradle-plugin", version.ref = "sonarqube" }
spring-bom = { module = "org.springframework:spring-framework-bom", version.ref = "spring" }
spring-core = { module = "org.springframework:spring-core", version.ref = "spring" }
spring-web = { module = "org.springframework:spring-web", version.ref = "spring" }
test-retry-gradle = { module = "org.gradle:test-retry-gradle-plugin", version.ref = "test-retry" }
