name: Trivy Vulnerability Scan (Repo mode)

on:
  workflow_dispatch:
    inputs:
      config-path:
        description: 'Relative path to Trivy config file'
        default: '.github/trivy-to-console.yaml'
        required: false
        type: string
      upload-results:
        description: 'Upload scan results to Github?'
        default: false
        required: false
        type: boolean
  workflow_call:
    inputs:
      config-path:
        description: 'Relative path to Trivy config file'
        default: '.github/trivy-to-console.yaml'
        required: false
        type: string
      upload-results:
        description: 'Upload scan results to Github?'
        default: false
        required: false
        type: boolean

jobs:
  run_trivy_scan:
    name: Run Trivy Scan
    runs-on: ubuntu-latest
    env:
      LOCAL_REPOSITORY_PATH: ./build/publications/repos
    steps:
      - uses: actions/checkout@v3
      - uses: spring-io/spring-gradle-build-action@v2
      - name: Publish to local repo (poms)
        run: |
          ./gradlew publishMavenJavaPublicationToLocalRepository
      - name: Run Trivy scan in repo mode (fs)
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          scan-ref: '${{ env.LOCAL_REPOSITORY_PATH }}/org/springframework/pulsar'
          trivy-config: ${{ inputs.config-path }}
      - name: Upload Trivy scan results to GitHub Security tab
        if: inputs.upload-results
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: 'trivy-results.sarif'
