name: Update to next Spring Boot version

on:
  workflow_dispatch:
    inputs:
      base-branch:
        description: "Base branch to update (e.g. '1.2.x'). HOWEVER always use workflow from: main"
        required: true
        type: string
permissions:
  contents: read

jobs:
  update_boot_version:
    name: Update Spring Boot version
    if: github.repository == 'spring-projects/spring-pulsar'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: read
    steps:
      - uses: actions/checkout@v6
        with:
          ref: ${{ inputs.base-branch }}
          token: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
      - name: Set up Gradle w/ Java 17 (0.x)
        if: inputs.base-branch == '1.2.x'
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '17'
          distribution: 'temurin'
      - name: Set up Gradle w/ Java 25 (main)
        if: inputs.base-branch != '1.2.x'
        uses: spring-io/spring-gradle-build-action@v2
        with:
          java-version: '25'
          distribution: 'liberica'
      - name: Update version and create PR
        env:
          GH_TOKEN: ${{ secrets.GH_ACTIONS_REPO_TOKEN }}
          BASE_BRANCH: ${{ inputs.base-branch }}
        run: |
          bootVersion=$(cat gradle/libs.versions.toml | grep "spring-boot = \"" | cut -d '"' -f2)
          echo "Current Spring Boot version is $bootVersion"
          milestone=$(cat gradle.properties | grep "version=" | awk -F'=' '{print $2}')
          milestone="${milestone%-*}"
          echo "Current milestone is $milestone"
          workBranch="update-boot-$bootVersion"
          echo "Work branch is $workBranch (based from $BASE_BRANCH)"

          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'          
          git fetch origin
          git checkout -b $workBranch origin/$BASE_BRANCH
  
          ./gradlew updateToNextBootSnapshotVersion
          bootVersion=$(cat gradle/libs.versions.toml | grep "spring-boot = \"" | cut -d '"' -f2)
          echo "Next Spring Boot version is $bootVersion"

          git commit -am "Update to Spring Boot $bootVersion"
          git push origin $workBranch

          gh pr create --title "Update Spring Boot to $bootVersion" \
            --body "Merge to update to next Spring Boot version." \
            --base $BASE_BRANCH \
            --label "type: dependency-upgrade" \
            --milestone $milestone
